### ISSUE TITLE
Configuring node-exporter to monitor CPU utilization metrics

### ISSUE THREAD

**Issue by knarayan** [sustainable-computing-io/peaks#32]
- Run below commands to configure [Prometheus](https://github.com/prometheus-operator/kube-prometheus/tree/main#quickstart) from the `kube-prometheus` directory.
  - Teardown existing installation using `kubectl delete --ignore-not-found=true -f manifests/ -f manifests/setup`
  - And trigger a fresh installation using `kubectl apply --server-side -f manifests/setup -f manifests`
- Assuming the namespace “monitoring” was used for Prometheus installation, use the same namespace in the file “node-exporter.yaml” for node-exporter installation.
- Run the command `kubectl apply -f node-exporter.yaml`
  - If it fails with an error `no matches for kind "DaemonSet" in version "apps/v1"` (which is only applicable for K8s 1.1.7 and above), then use an [appropriate version](https://github.com/gluster/gluster-kubernetes/issues/627#issuecomment-569465572) “extensions/v1” or "extensions/v1beta1".
- Ensure that node-exporter service is available.
  - `kubectl get svc -n monitoring` 
- Port forward `node-exporter`
  - `kubectl port-forward svc/node-exporter 9100 -n monitoring`
- Check that the node-level metric `node_cpu_seconds_total` is available in `node-exporter` service.
  - `curl http://localhost:9100/metrics | grep node_cpu_seconds_total`
- Port forward `prometheus-k8s`
  - `kubectl port-forward svc/prometheus-k8s 9090 -n monitoring`
- Check that the node-level metric `node_cpu_seconds_total` is available in `prometheus-k8s` service.
  - `curl 'http://localhost:9090/api/v1/label/__name__/values' | grep node_cpu_seconds_total`

**Comment by knarayan** [comment]
When using `kepler-model-server` [script](https://github.com/sustainable-computing-io/kepler-model-server/tree/main/model_training#1-prepare-cluster) for `kind` cluster preparation, `node-exporter` service is not configured by default. Above procedure can be used to configure it.

**Comment by knarayan** [comment]
Content of the file `node-exporter.yaml`
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: node-exporter
    spec:
      containers:
      - args:
        - --web.listen-address=0.0.0.0:9100
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        image: quay.io/prometheus/node-exporter:v0.18.1
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: node-exporter
    serviceMonitorSelector: prometheus-k8s
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    targetPort: 9100
  jobLabel: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: node-exporter
```
